export const designTokens = {
  page: 'pb-20',
  pageHeader: 'mb-8 flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-end',
  pageTitle: 'text-2xl sm:text-3xl font-bold mb-2',
  pageIntro: 'text-sm text-text-secondary sm:text-base',
  pageSectionStack: 'space-y-6',
  sectionGrid: 'gap-6',
  sectionCard: 'rounded-3xl border border-border bg-card p-6 shadow-sm',
  sectionCardDense: 'rounded-3xl border border-border bg-card p-5 sm:p-6 shadow-sm',
  itemCard: 'rounded-2xl border border-border p-4 sm:p-5',
  itemCardCompact: 'rounded-2xl border border-border p-4',
  input: 'w-full rounded-xl border border-border bg-background px-4 py-3 outline-none transition-all focus:border-brand-primary',
  inputOnCard: 'w-full rounded-xl border border-border bg-card px-4 py-3 outline-none transition-all focus:border-brand-primary',
  modalPanel: 'relative w-full max-w-md rounded-[2rem] border border-border bg-card p-8 shadow-2xl',
  modalPanelWide: 'w-full rounded-[2rem] border border-border bg-card shadow-lg',
  cardTitle: 'text-xl font-bold',
  metaText: 'text-xs text-text-secondary',
  microBadge: 'text-[10px] font-bold uppercase tracking-wider',
  toolbarGap: 'gap-3',
  listStack: 'space-y-3',
  listStackRelaxed: 'space-y-4',
  swatch: 'flex h-11 w-11 items-center justify-center rounded-2xl transition-all',
  brandMark: 'flex h-10 w-10 items-center justify-center rounded-xl',
  brandMarkIcon: 'h-6 w-6'
} as const;
